version: '2'
services:
#----------------------------------------------
  db:
    image: mariadb:10.3
    container_name: db
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_ROOT_PASSWORD=
    restart: unless-stopped
#----------------------------------------------
  keyserver:
    image: lals1/keyserver:latest
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
     - db
#----------------------------------------------
